name: sansblok
version: '1.0'
main: com.lime.sansblok.SansBlok
api-version: '1.16'
depend:
  - FancyHolograms
commands:
  sansblok:
    description: Sans blogu ana komutu.
    permission: sansblok.admin
